services:
  - type: web
    name: babel-factory
    runtime: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
