services:
  - type: web
    name: babel-factory
    runtime: node
    plan: starter
    region: oregon
    branch: main
    repo: https://github.com/nisbus/babel-factory
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
